curl --output KC.png https://aviata.kz/static/airline-logos/80x80/KC.png
curl --output HY.png https://aviata.kz/static/airline-logos/80x80/HY.png
curl --output EK.png https://aviata.kz/static/airline-logos/80x80/EK.png
curl --output HR.png https://aviata.kz/static/airline-logos/80x80/HR.png
curl --output FZ.png https://aviata.kz/static/airline-logos/80x80/FZ.png
curl --output S7.png https://aviata.kz/static/airline-logos/80x80/S7.png
curl --output LH.png https://aviata.kz/static/airline-logos/80x80/LH.png
curl --output BT.png https://aviata.kz/static/airline-logos/80x80/BT.png
curl --output CZ.png https://aviata.kz/static/airline-logos/80x80/CZ.png
curl --output SU.png https://aviata.kz/static/airline-logos/80x80/SU.png
curl --output B2.png https://aviata.kz/static/airline-logos/80x80/B2.png
curl --output DV.png https://aviata.kz/static/airline-logos/80x80/DV.png
curl --output TK.png https://aviata.kz/static/airline-logos/80x80/TK.png